const express =require("express")
const cors = require ("cors")
const env =require("dotenv").config()
const port=5000
const app =express()
//pour relier avec la base de donnee
const connectdb=require("./database")
connectdb()
app.use(express.json())
// autorisation 
app.use(cors())
const OfferRouter=require("./route/OfferRouter")
app.use("/offer",OfferRouter)
const UserRouter=require("./route/UserRouter")
app.use("/user",UserRouter)
const RecruiterRouter=require("./route/RecruiterRouter")
app.use("/recruiter",RecruiterRouter)
const CandidatureRouter=require("./route/CandidatureRouter")
app.use("/candidature",CandidatureRouter)
const CandidateRouter = require("./route/CandidateRouter")
app.use("/candidate", CandidateRouter)
const CategorieRouter = require("./route/CategorieRouter")
app.use("/categorie", CategorieRouter)
const SkillRouter = require("./route/SkillRouter")
app.use("/skill", SkillRouter)
const EducationRouter = require("./route/EducationRouter")
app.use("/education", EducationRouter)
const CertificationRouter = require("./route/CertificationRouter")
app.use("/certification", CertificationRouter)
const InterviewEventRouter = require("./route/InterviewEventRouter")
app.use("/interviewevent", InterviewEventRouter)
const ExperienceRouter = require("./route/ExperienceRouter")
const res = require("express/lib/response")
app.use("/experience", ExperienceRouter)
//pour afficher une image on utilise ce url
app.get("/:image",(req,res)=>{res.sendFile(__dirname+"/uploads/"+req.params.image)})

app.listen(port,function(){
    console.log(`the server is running with ${process.env.PORT} open at http://localhost:${process.env.PORT}`)})